# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yzs/my-WebServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yzs/my-WebServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yzs/my-WebServer/CMakeFiles /home/yzs/my-WebServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yzs/my-WebServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_WebServer

# Build rule for target.
my_WebServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_WebServer
.PHONY : my_WebServer

# fast build rule for target.
my_WebServer/fast:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/build
.PHONY : my_WebServer/fast

codes/buffer.o: codes/buffer.cpp.o

.PHONY : codes/buffer.o

# target to build an object file
codes/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/buffer.cpp.o
.PHONY : codes/buffer.cpp.o

codes/buffer.i: codes/buffer.cpp.i

.PHONY : codes/buffer.i

# target to preprocess a source file
codes/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/buffer.cpp.i
.PHONY : codes/buffer.cpp.i

codes/buffer.s: codes/buffer.cpp.s

.PHONY : codes/buffer.s

# target to generate assembly for a file
codes/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/buffer.cpp.s
.PHONY : codes/buffer.cpp.s

codes/epoller.o: codes/epoller.cpp.o

.PHONY : codes/epoller.o

# target to build an object file
codes/epoller.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/epoller.cpp.o
.PHONY : codes/epoller.cpp.o

codes/epoller.i: codes/epoller.cpp.i

.PHONY : codes/epoller.i

# target to preprocess a source file
codes/epoller.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/epoller.cpp.i
.PHONY : codes/epoller.cpp.i

codes/epoller.s: codes/epoller.cpp.s

.PHONY : codes/epoller.s

# target to generate assembly for a file
codes/epoller.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/epoller.cpp.s
.PHONY : codes/epoller.cpp.s

codes/heaptimer.o: codes/heaptimer.cpp.o

.PHONY : codes/heaptimer.o

# target to build an object file
codes/heaptimer.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/heaptimer.cpp.o
.PHONY : codes/heaptimer.cpp.o

codes/heaptimer.i: codes/heaptimer.cpp.i

.PHONY : codes/heaptimer.i

# target to preprocess a source file
codes/heaptimer.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/heaptimer.cpp.i
.PHONY : codes/heaptimer.cpp.i

codes/heaptimer.s: codes/heaptimer.cpp.s

.PHONY : codes/heaptimer.s

# target to generate assembly for a file
codes/heaptimer.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/heaptimer.cpp.s
.PHONY : codes/heaptimer.cpp.s

codes/httpconn.o: codes/httpconn.cpp.o

.PHONY : codes/httpconn.o

# target to build an object file
codes/httpconn.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpconn.cpp.o
.PHONY : codes/httpconn.cpp.o

codes/httpconn.i: codes/httpconn.cpp.i

.PHONY : codes/httpconn.i

# target to preprocess a source file
codes/httpconn.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpconn.cpp.i
.PHONY : codes/httpconn.cpp.i

codes/httpconn.s: codes/httpconn.cpp.s

.PHONY : codes/httpconn.s

# target to generate assembly for a file
codes/httpconn.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpconn.cpp.s
.PHONY : codes/httpconn.cpp.s

codes/httprequest.o: codes/httprequest.cpp.o

.PHONY : codes/httprequest.o

# target to build an object file
codes/httprequest.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httprequest.cpp.o
.PHONY : codes/httprequest.cpp.o

codes/httprequest.i: codes/httprequest.cpp.i

.PHONY : codes/httprequest.i

# target to preprocess a source file
codes/httprequest.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httprequest.cpp.i
.PHONY : codes/httprequest.cpp.i

codes/httprequest.s: codes/httprequest.cpp.s

.PHONY : codes/httprequest.s

# target to generate assembly for a file
codes/httprequest.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httprequest.cpp.s
.PHONY : codes/httprequest.cpp.s

codes/httpresponse.o: codes/httpresponse.cpp.o

.PHONY : codes/httpresponse.o

# target to build an object file
codes/httpresponse.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpresponse.cpp.o
.PHONY : codes/httpresponse.cpp.o

codes/httpresponse.i: codes/httpresponse.cpp.i

.PHONY : codes/httpresponse.i

# target to preprocess a source file
codes/httpresponse.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpresponse.cpp.i
.PHONY : codes/httpresponse.cpp.i

codes/httpresponse.s: codes/httpresponse.cpp.s

.PHONY : codes/httpresponse.s

# target to generate assembly for a file
codes/httpresponse.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpresponse.cpp.s
.PHONY : codes/httpresponse.cpp.s

codes/io_thread.o: codes/io_thread.cc.o

.PHONY : codes/io_thread.o

# target to build an object file
codes/io_thread.cc.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/io_thread.cc.o
.PHONY : codes/io_thread.cc.o

codes/io_thread.i: codes/io_thread.cc.i

.PHONY : codes/io_thread.i

# target to preprocess a source file
codes/io_thread.cc.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/io_thread.cc.i
.PHONY : codes/io_thread.cc.i

codes/io_thread.s: codes/io_thread.cc.s

.PHONY : codes/io_thread.s

# target to generate assembly for a file
codes/io_thread.cc.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/io_thread.cc.s
.PHONY : codes/io_thread.cc.s

codes/log.o: codes/log.cpp.o

.PHONY : codes/log.o

# target to build an object file
codes/log.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/log.cpp.o
.PHONY : codes/log.cpp.o

codes/log.i: codes/log.cpp.i

.PHONY : codes/log.i

# target to preprocess a source file
codes/log.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/log.cpp.i
.PHONY : codes/log.cpp.i

codes/log.s: codes/log.cpp.s

.PHONY : codes/log.s

# target to generate assembly for a file
codes/log.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/log.cpp.s
.PHONY : codes/log.cpp.s

codes/redisconnpool.o: codes/redisconnpool.cpp.o

.PHONY : codes/redisconnpool.o

# target to build an object file
codes/redisconnpool.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/redisconnpool.cpp.o
.PHONY : codes/redisconnpool.cpp.o

codes/redisconnpool.i: codes/redisconnpool.cpp.i

.PHONY : codes/redisconnpool.i

# target to preprocess a source file
codes/redisconnpool.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/redisconnpool.cpp.i
.PHONY : codes/redisconnpool.cpp.i

codes/redisconnpool.s: codes/redisconnpool.cpp.s

.PHONY : codes/redisconnpool.s

# target to generate assembly for a file
codes/redisconnpool.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/redisconnpool.cpp.s
.PHONY : codes/redisconnpool.cpp.s

codes/sqlconnpoll.o: codes/sqlconnpoll.cpp.o

.PHONY : codes/sqlconnpoll.o

# target to build an object file
codes/sqlconnpoll.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/sqlconnpoll.cpp.o
.PHONY : codes/sqlconnpoll.cpp.o

codes/sqlconnpoll.i: codes/sqlconnpoll.cpp.i

.PHONY : codes/sqlconnpoll.i

# target to preprocess a source file
codes/sqlconnpoll.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/sqlconnpoll.cpp.i
.PHONY : codes/sqlconnpoll.cpp.i

codes/sqlconnpoll.s: codes/sqlconnpoll.cpp.s

.PHONY : codes/sqlconnpoll.s

# target to generate assembly for a file
codes/sqlconnpoll.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/sqlconnpoll.cpp.s
.PHONY : codes/sqlconnpoll.cpp.s

codes/webserver.o: codes/webserver.cpp.o

.PHONY : codes/webserver.o

# target to build an object file
codes/webserver.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/webserver.cpp.o
.PHONY : codes/webserver.cpp.o

codes/webserver.i: codes/webserver.cpp.i

.PHONY : codes/webserver.i

# target to preprocess a source file
codes/webserver.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/webserver.cpp.i
.PHONY : codes/webserver.cpp.i

codes/webserver.s: codes/webserver.cpp.s

.PHONY : codes/webserver.s

# target to generate assembly for a file
codes/webserver.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/webserver.cpp.s
.PHONY : codes/webserver.cpp.s

codes/xjwt.o: codes/xjwt.cpp.o

.PHONY : codes/xjwt.o

# target to build an object file
codes/xjwt.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/xjwt.cpp.o
.PHONY : codes/xjwt.cpp.o

codes/xjwt.i: codes/xjwt.cpp.i

.PHONY : codes/xjwt.i

# target to preprocess a source file
codes/xjwt.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/xjwt.cpp.i
.PHONY : codes/xjwt.cpp.i

codes/xjwt.s: codes/xjwt.cpp.s

.PHONY : codes/xjwt.s

# target to generate assembly for a file
codes/xjwt.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/xjwt.cpp.s
.PHONY : codes/xjwt.cpp.s

coroutine/coctx_swap.o: coroutine/coctx_swap.S.o

.PHONY : coroutine/coctx_swap.o

# target to build an object file
coroutine/coctx_swap.S.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/coctx_swap.S.o
.PHONY : coroutine/coctx_swap.S.o

coroutine/coroutine.o: coroutine/coroutine.cc.o

.PHONY : coroutine/coroutine.o

# target to build an object file
coroutine/coroutine.cc.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/coroutine.cc.o
.PHONY : coroutine/coroutine.cc.o

coroutine/coroutine.i: coroutine/coroutine.cc.i

.PHONY : coroutine/coroutine.i

# target to preprocess a source file
coroutine/coroutine.cc.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/coroutine.cc.i
.PHONY : coroutine/coroutine.cc.i

coroutine/coroutine.s: coroutine/coroutine.cc.s

.PHONY : coroutine/coroutine.s

# target to generate assembly for a file
coroutine/coroutine.cc.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/coroutine.cc.s
.PHONY : coroutine/coroutine.cc.s

coroutine/coroutine_hook.o: coroutine/coroutine_hook.cc.o

.PHONY : coroutine/coroutine_hook.o

# target to build an object file
coroutine/coroutine_hook.cc.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/coroutine_hook.cc.o
.PHONY : coroutine/coroutine_hook.cc.o

coroutine/coroutine_hook.i: coroutine/coroutine_hook.cc.i

.PHONY : coroutine/coroutine_hook.i

# target to preprocess a source file
coroutine/coroutine_hook.cc.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/coroutine_hook.cc.i
.PHONY : coroutine/coroutine_hook.cc.i

coroutine/coroutine_hook.s: coroutine/coroutine_hook.cc.s

.PHONY : coroutine/coroutine_hook.s

# target to generate assembly for a file
coroutine/coroutine_hook.cc.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/coroutine_hook.cc.s
.PHONY : coroutine/coroutine_hook.cc.s

coroutine/coroutine_pool.o: coroutine/coroutine_pool.cc.o

.PHONY : coroutine/coroutine_pool.o

# target to build an object file
coroutine/coroutine_pool.cc.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/coroutine_pool.cc.o
.PHONY : coroutine/coroutine_pool.cc.o

coroutine/coroutine_pool.i: coroutine/coroutine_pool.cc.i

.PHONY : coroutine/coroutine_pool.i

# target to preprocess a source file
coroutine/coroutine_pool.cc.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/coroutine_pool.cc.i
.PHONY : coroutine/coroutine_pool.cc.i

coroutine/coroutine_pool.s: coroutine/coroutine_pool.cc.s

.PHONY : coroutine/coroutine_pool.s

# target to generate assembly for a file
coroutine/coroutine_pool.cc.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/coroutine_pool.cc.s
.PHONY : coroutine/coroutine_pool.cc.s

coroutine/memory.o: coroutine/memory.cc.o

.PHONY : coroutine/memory.o

# target to build an object file
coroutine/memory.cc.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/memory.cc.o
.PHONY : coroutine/memory.cc.o

coroutine/memory.i: coroutine/memory.cc.i

.PHONY : coroutine/memory.i

# target to preprocess a source file
coroutine/memory.cc.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/memory.cc.i
.PHONY : coroutine/memory.cc.i

coroutine/memory.s: coroutine/memory.cc.s

.PHONY : coroutine/memory.s

# target to generate assembly for a file
coroutine/memory.cc.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/coroutine/memory.cc.s
.PHONY : coroutine/memory.cc.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/main.cpp.s
.PHONY : main.cpp.s

net/fd_event.o: net/fd_event.cc.o

.PHONY : net/fd_event.o

# target to build an object file
net/fd_event.cc.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/fd_event.cc.o
.PHONY : net/fd_event.cc.o

net/fd_event.i: net/fd_event.cc.i

.PHONY : net/fd_event.i

# target to preprocess a source file
net/fd_event.cc.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/fd_event.cc.i
.PHONY : net/fd_event.cc.i

net/fd_event.s: net/fd_event.cc.s

.PHONY : net/fd_event.s

# target to generate assembly for a file
net/fd_event.cc.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/fd_event.cc.s
.PHONY : net/fd_event.cc.s

net/mutex.o: net/mutex.cc.o

.PHONY : net/mutex.o

# target to build an object file
net/mutex.cc.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/mutex.cc.o
.PHONY : net/mutex.cc.o

net/mutex.i: net/mutex.cc.i

.PHONY : net/mutex.i

# target to preprocess a source file
net/mutex.cc.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/mutex.cc.i
.PHONY : net/mutex.cc.i

net/mutex.s: net/mutex.cc.s

.PHONY : net/mutex.s

# target to generate assembly for a file
net/mutex.cc.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/mutex.cc.s
.PHONY : net/mutex.cc.s

net/reactor.o: net/reactor.cc.o

.PHONY : net/reactor.o

# target to build an object file
net/reactor.cc.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/reactor.cc.o
.PHONY : net/reactor.cc.o

net/reactor.i: net/reactor.cc.i

.PHONY : net/reactor.i

# target to preprocess a source file
net/reactor.cc.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/reactor.cc.i
.PHONY : net/reactor.cc.i

net/reactor.s: net/reactor.cc.s

.PHONY : net/reactor.s

# target to generate assembly for a file
net/reactor.cc.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/reactor.cc.s
.PHONY : net/reactor.cc.s

net/timer.o: net/timer.cc.o

.PHONY : net/timer.o

# target to build an object file
net/timer.cc.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/timer.cc.o
.PHONY : net/timer.cc.o

net/timer.i: net/timer.cc.i

.PHONY : net/timer.i

# target to preprocess a source file
net/timer.cc.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/timer.cc.i
.PHONY : net/timer.cc.i

net/timer.s: net/timer.cc.s

.PHONY : net/timer.s

# target to generate assembly for a file
net/timer.cc.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/net/timer.cc.s
.PHONY : net/timer.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... my_WebServer"
	@echo "... codes/buffer.o"
	@echo "... codes/buffer.i"
	@echo "... codes/buffer.s"
	@echo "... codes/epoller.o"
	@echo "... codes/epoller.i"
	@echo "... codes/epoller.s"
	@echo "... codes/heaptimer.o"
	@echo "... codes/heaptimer.i"
	@echo "... codes/heaptimer.s"
	@echo "... codes/httpconn.o"
	@echo "... codes/httpconn.i"
	@echo "... codes/httpconn.s"
	@echo "... codes/httprequest.o"
	@echo "... codes/httprequest.i"
	@echo "... codes/httprequest.s"
	@echo "... codes/httpresponse.o"
	@echo "... codes/httpresponse.i"
	@echo "... codes/httpresponse.s"
	@echo "... codes/io_thread.o"
	@echo "... codes/io_thread.i"
	@echo "... codes/io_thread.s"
	@echo "... codes/log.o"
	@echo "... codes/log.i"
	@echo "... codes/log.s"
	@echo "... codes/redisconnpool.o"
	@echo "... codes/redisconnpool.i"
	@echo "... codes/redisconnpool.s"
	@echo "... codes/sqlconnpoll.o"
	@echo "... codes/sqlconnpoll.i"
	@echo "... codes/sqlconnpoll.s"
	@echo "... codes/webserver.o"
	@echo "... codes/webserver.i"
	@echo "... codes/webserver.s"
	@echo "... codes/xjwt.o"
	@echo "... codes/xjwt.i"
	@echo "... codes/xjwt.s"
	@echo "... coroutine/coctx_swap.o"
	@echo "... coroutine/coroutine.o"
	@echo "... coroutine/coroutine.i"
	@echo "... coroutine/coroutine.s"
	@echo "... coroutine/coroutine_hook.o"
	@echo "... coroutine/coroutine_hook.i"
	@echo "... coroutine/coroutine_hook.s"
	@echo "... coroutine/coroutine_pool.o"
	@echo "... coroutine/coroutine_pool.i"
	@echo "... coroutine/coroutine_pool.s"
	@echo "... coroutine/memory.o"
	@echo "... coroutine/memory.i"
	@echo "... coroutine/memory.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... net/fd_event.o"
	@echo "... net/fd_event.i"
	@echo "... net/fd_event.s"
	@echo "... net/mutex.o"
	@echo "... net/mutex.i"
	@echo "... net/mutex.s"
	@echo "... net/reactor.o"
	@echo "... net/reactor.i"
	@echo "... net/reactor.s"
	@echo "... net/timer.o"
	@echo "... net/timer.i"
	@echo "... net/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

